# Generated by Django 5.0 on 2023-12-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='354342598237', max_length=15, verbose_name='Проверочный код'),
        ),
    ]
