# Generated by Django 5.0 on 2023-12-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_ver_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ver_code',
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default='54959', max_length=15, verbose_name='код'),
        ),
    ]
