# Generated by Django 5.0 on 2023-12-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_ver_code_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='77472', max_length=15, verbose_name='код'),
        ),
    ]
