# Generated by Django 4.2.7 on 2023-11-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoties',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='фото'),
        ),
    ]
