# Generated by Django 4.2.7 on 2023-11-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_categoties_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoties',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Categoties/', verbose_name='фото'),
        ),
    ]
