# Generated by Django 4.2.7 on 2023-11-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_categoties_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoties',
            name='descripsions',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='categoties',
            name='image',
            field=models.ImageField(upload_to='Categoties/', verbose_name='фото'),
        ),
    ]
