# Generated by Django 4.2.7 on 2023-11-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_categoties_descripsions_alter_categoties_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoties',
            old_name='descripsions',
            new_name='descriptions',
        ),
    ]
