# Generated by Django 4.2.7 on 2023-12-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_descripsions_categoties_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=150, verbose_name='slug')),
                ('body', models.TextField(verbose_name='Содержимое')),
                ('photo', models.ImageField(upload_to='photo/', verbose_name='Превью')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('on_published', models.BooleanField(default=True, verbose_name='статус')),
                ('count_view', models.IntegerField(default=0, verbose_name='соличество просмотров')),
            ],
        ),
    ]
