# Generated by Django 4.2.7 on 2023-12-01 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блоговые записи'},
        ),
    ]
