# Generated by Django 4.2.7 on 2023-12-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_block_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='count_view',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='соличество просмотров'),
        ),
        migrations.AlterField(
            model_name='block',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='block',
            name='on_published',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='статус'),
        ),
    ]
