# Generated by Django 4.2.7 on 2023-12-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_block_count_view_alter_block_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='count_view',
            field=models.PositiveIntegerField(default=0, verbose_name='соличество просмотров'),
        ),
    ]
