# Generated by Django 5.0 on 2023-12-11 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_contact_alter_product_data_last_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb_versions', models.IntegerField(blank=True, null=True, verbose_name='номер версии')),
                ('name_versions', models.IntegerField(max_length=150, verbose_name='номер версии')),
                ('is_active', models.BooleanField(default=True, verbose_name='активная версия')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='продукт')),
            ],
        ),
    ]
