# Generated by Django 5.0 on 2023-12-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_versions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versions',
            options={'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
        migrations.AlterField(
            model_name='versions',
            name='name_versions',
            field=models.CharField(max_length=150, verbose_name='номер версии'),
        ),
    ]
